# Spring Boot 多线程示例应用配置
server:
  port: 8080
  servlet:
    context-path: /chapter13Async

spring:
  application:
    name: chapter13Async-multithreading-demo

# 日志配置
logging:
  level:
    "org.springframework.web": INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
