server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
    # Nacos服务发现配置
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: microservice-auth
        group: DEFAULT_GROUP
        service: ${spring.application.name}
        cluster-name: default
        username: nacos
        password: nacos
        metadata:
          version: 1.0.0
          author: microservice-team
        register-enabled: true
        heartbeat-interval: 5000
        heartbeat-timeout: 15000

# JWT配置
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400  # 24小时（秒）
  issuer: microservice-auth  # JWT签发者
  audience: gateway  # JWT受众

# Keycloak配置
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: microservice-realm
  resource: gateway-client
  public-client: false
  credentials:
    secret: your-gateway-client-secret

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
