server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  # 服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: microservice-auth

# JWT配置
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400  # 24小时

# Keycloak配置
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: microservice-realm
  resource: gateway-client
  public-client: false
  credentials:
    secret: your-gateway-client-secret

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
