# Spring Boot ActiveMQ 示例应用配置
server:
  port: 8080
  servlet:
    context-path: /chapter13Mq

spring:
  application:
    name: chapter13Mq-activemq-demo
  
  # ActiveMQ配置
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000
      expiry-timeout: 0
      max-active-session-per-connection: 500
      block-if-session-pool-is-full: true
      block-if-session-pool-is-full-timeout: -1
      create-connection-on-startup: true
      time-between-expiration-check-millis: 15000
      reconnect-on-exception: true

  # JMS配置
  jms:
    # 是否启用JMS
    enabled: true
    # 默认目标类型 (queue 或 topic)
    pub-sub-domain: false
    # 消息转换器
    template:
      default-destination: default.queue
      delivery-mode: persistent
      time-to-live: 60000
      priority: 4
    # 监听器配置
    listener:
      acknowledge-mode: auto

# 日志配置
logging:
  level:
    "org.example.chapter14": DEBUG
    "org.springframework.jms": DEBUG
    "org.apache.activemq": INFO
    "org.springframework.web": INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 自定义配置 - ActiveMQ 队列和主题名称
activemq:
  # 队列名称
  queue:
    user: user.queue
    order: order.queue
    email: email.queue
    notification: notification.queue
  # 主题名称
  topic:
    news: news.topic
    weather: weather.topic
    stock: stock.topic
